### ISSUE TITLE
请问如何手动更新数据库？

### ISSUE THREAD

**Issue by flyingghost** [zhuzhichao/ip-location-zh#15]
离线数据库更新日期已经过去半年多了，可否提供方法可随时手动更新数据库？例如，更新脚本。
或者，不方便的话告知dat文件格式和更新逻辑也可以。
谢谢！

**Comment by shiny** [comment]
dat 文件该更新了

**Comment by zhuzhichao** [comment]
@flyingghost @shiny 谢谢提醒，已经更新到最新的数据库了。请更新版本到 2.3.0 即可
