### ISSUE TITLE
我用tp5报错（Fatal error: Uncaught think\exception\ErrorException: fclose(): supplied resource is not a valid stream resource），大家用的时候都没有吗

### ISSUE THREAD

**Issue by xqmGitHub** [zhuzhichao/ip-location-zh#18]
`Fatal error: Uncaught think\exception\ErrorException: fclose(): supplied resource is not a valid stream resource`
zhuzhichao\ip-location-zh\src\Ip.php on line 247
fclose() 的时候应该多加一个判断 is_resource(self::$fp)

```
if (self::$fp !== null && is_resource(self::$fp)) {
      fclose(self::$fp);
}
```

这样就阔以了

**Comment by zhuzhichao** [comment]
我自己测试没发现这样的问题，没有其他人报这样的错误。是否是你的运行环境有些问题？
