### ISSUE TITLE
邮政编码不正确

### ISSUE THREAD

**Issue by chanjsq** [zhuzhichao/ip-location-zh#20]
试了 `101.226.178.189`（上海）、`180.97.33.108`（南京），都是错的。

有时间我提一个 PR。

**Comment by zhuzhichao** [comment]
返回的不是邮编，是行政区划代码。https://baike.baidu.com/item/%E8%A1%8C%E6%94%BF%E5%8C%BA%E5%88%92%E4%BB%A3%E7%A0%81

这个是没有问题的。

**Comment by chanjsq** [comment]
哦哦。理解错啦，感谢纠正。
