### ISSUE TITLE
有没有跟进官方新版数据库的计划？

### ISSUE THREAD

**Issue by hankclc** [zhuzhichao/ip-location-zh#22]
请问有没有跟进官方新版数据库的计划？
你这个cityid挺好用的，我基本就靠这个定位了

**Comment by zhuzhichao** [comment]
谢谢支持。有这个计划的，官方的数据格式有调整，后面会更新的。

**Comment by zhuzhichao** [comment]
@hankclc 已经更新了， `composer update zhuzhichao/ip-location-zh`
