### ISSUE TITLE
composer.json的psr-4写错了吧？

### ISSUE THREAD

**Issue by hugtale** [zhuzhichao/ip-location-zh#5]

**Comment by zhuzhichao** [comment]
你好，谢谢关注这个项目。

我觉得应该没有什么问题的。你可以看一下https://github.com/PizzaLiu/PHP-FIG/blob/master/PSR-4-autoloader-cn.md。

同时你看一下这个项目的 composer.json 文件 https://github.com/thephpleague/climate/blob/master/composer.json。

我这里意思是 Zhuzhichao\IpLocationZh\  作为命名空间前缀，而Zhuzhichao\IpLocationZh\的根目录是 src。

如有问题，欢迎指出

**Comment by hugtale** [comment]
这包能用composer，主要是因为这句话：`"files": ["src/IpLocationZh.php"],`

**Comment by zhuzhichao** [comment]
你说的对，谢谢指正！👍  很羞愧啊，确实是自己写的不够规范！已经更新了。
