### ISSUE TITLE
这个包可以进行压缩吗？

### ISSUE THREAD

**Issue by vipwei** [zhuzhichao/ip-location-zh#9]
我只想让他来判断是不是中国的IP就可以

**Comment by zhuzhichao** [comment]
自己写一个方法判断吧, 很简单的

`return Ip::find('8.8.8.8')[0] == '中国';`

**Comment by vipwei** [comment]
嗯，现在我也是用的这个方法，不过数据包太大了 哈哈...就是想缩减一下数据包

**Comment by WinEcos** [comment]
require 'vendor/autoload.php';  
use Zhuzhichao\IpLocationZh\Ip;  
var_dump(Ip::find('1.192.94.203'));

第2句式什么意思？使用包嘛？

**Comment by zhuzhichao** [comment]
@WinEcos 这里是要使用的类的命名空间。
